name: myenv
channels:
  - defaults
  - conda-forge
  - anaconda  
dependencies:
  - python=3.8
  - pandas=1.3.0
  - numpy=1.19.5
  - tensorflow=2.5.0
  - keras=2.4.3
  - scikit-learn=0.24.2
  - pillow=8.3.1
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - tqdm=4.61.2
  - requests=2.25.1
  - pip
  - pip:
    - tensorflow-addons==0.13.0
    - csv 
